---
title: "Assignment 2"
author: "79546 - Stephen K. Ng'etich"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
---

```{r}
knitr::opts_chunk$set(fig.width=6, fig.height=6) 

```

# Pre-requisite
## install package
```{r message = FALSE,warning = FALSE}
#install.packages("readxl")
#install.packages('dplyr')
```

## load package
```{r message = FALSE,warning = FALSE}
# Clear variables
rm(list=ls())

library(readxl)
library(dplyr)
library(tidyverse)

```
## Load dataset

```{r}

# Load Dataset
dataset <- read_excel("dataset/Dataset2.xlsx")

```

# Exploratory Data Analysis

Convert `Region` column data type to `factor` 
```{r}
dataset$Region <- as.factor(dataset$Region)
```




## Summary statistic

```{r}
summary(dataset)
```

```{r}

plot(dataset)
```
[Interprating multidimention plot]

## Model selection
### Build the linear model

```{r}
power_lm_model = lm(Power~ .,data=dataset)
summary(power_lm_model)
```
From the summary, Homes
https://jbhender.github.io/Stats506/F17/Projects/Group21_Model_Selection.html


The following methods are used for model selection  
1. Stepwise regression
2. Akaike information criterion (AIC)

### Stepwise Regression
