---
title: "Assignment 3"
author: "79546 - Stephen K. Ng'etich"
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
---

```{r echo=FALSE}
knitr::opts_chunk$set(fig.width=6, fig.height=6) 

```

# Pre-requisite
## Load packages
```{r message = FALSE,warning = FALSE}
# Clear variables
rm(list=ls())

library(readxl)
library(dplyr)
library(tidyverse)
library(lattice)
library(leaps)
library(MASS)

```
## Load dataset

```{r}

# Load Dataset
dataset <- read_excel("dataset/Sales_Dataset.xlsx")

```

# Exploratory Data Analysis

```{r}
summary(dataset)
```
```{r}
plot(dataset)
```
From the visual inspection of the plot, the variables are all correlated since the plot shows a linear relationship and heads on one line.

## Model Selection
```{r}
lm_model = lm(Sales ~ . , data=dataset)
summary(lm_model)
```
Radio, Newspaper and TV has p-value greater than 0.05.This mean that they are not statically significant in predicting Sales

```{r}

lm_model1 = lm(Sales ~BillBoard+poly(TV,degree=2,raw = TRUE), data=dataset)  
#lm_model1 = lm(Sales ~BillBoard, data=dataset)  

summary(lm_model1)

```
```{r}
lm_model1 = lm(Sales ~ Newspaper + poly(Newspaper,raw=FALSE) , data=dataset)
summary(lm_model1)
```

```{r}
lm_model2 = lm(Sales ~ . + Radio*Newspaper , data=dataset)
summary(lm_model2)
```
```{r}
lm_model3 = lm(Sales ~ ., data=dataset)
summary(lm_model1)
```

